version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"  # Expose port 8080
    volumes:
      - .:/app  # Mount the current directory into the container
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    environment:
      - PORT=8080  # Set the port environment variable
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M